###############################################################
# Program:
#     Checkpoint 05b, Constructors
#     Brother Alvey, CS165
# Author:
#     Jared Thomasson
# Summary:
#     Uses construction file to teach about constructors.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : money.h money.cpp check05b.cpp
	g++ money.cpp check05b.cpp

